apiVersion: apps/v5
kind: Deployment
metadata:
  name: app
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        image: 540128513460.dkr.ecr.us-east-1.amazonaws.com/myapp_project2:v5.0
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: DBPORT 
          value: "3306"
        - name: DBPWD
          value: "pw123"
        - name: DBHOST
          value: "mysql.project-2a.svc.cluster.local"
        - name: DBUSER
          value: "root"


